---
name: orchestrator

secrets:
  aws_config:
    file: ./secrets/aws_config
  cyhy_read_creds:
    file: ./secrets/cyhy_read_creds.yml
  scan_read_creds:
    file: ./secrets/scan_read_creds.yml
  scan_write_creds:
    file: ./secrets/scan_write_creds.yml

services:
  gather:
    depends_on:
      - redis
    image: cisagov/gatherer:2.0.3
    secrets:
      - source: cyhy_read_creds
        target: database_creds.yml
    volumes:
      - ./output:/home/cisa/shared
  pshtt_report:
    depends_on:
      - redis
    image: cisagov/pshtt_reporter:1.4.1
    secrets:
      - source: scan_read_creds
        target: scan_read_creds.yml
    volumes:
      - ./output:/home/cisa/shared
  redis:
    image: redis:alpine
    # ports:
    #   - host_ip: 127.0.0.1
    #     mode: host
    #     protocol: tcp
    #     # Note that we expose redis on a non-standard port to avoid
    #     # conflict with the Admiral:
    #     # https://github.com/cisagov/ansible-role-admiral
    #     published: 6378
    #     target: 6379
  save:
    depends_on:
      - redis
    environment:
      - AWS_CONFIG_FILE=/run/secrets/aws_config
      - AWS_PROFILE=elasticsearch
      # Setting this environment variable ensures that the config file
      # (and not just any credentials file that is present) is loaded.
      - AWS_SDK_LOAD_CONFIG=1
    image: cisagov/saver:v1.6.1
    secrets:
      - source: aws_config
        target: aws_config
      - source: scan_write_creds
        target: scan_write_creds.yml
    volumes:
      - ./output:/home/cisa/shared
  scan:
    depends_on:
      - redis
    environment:
      - AWS_CONFIG_FILE=/run/secrets/aws_config
      - AWS_PROFILE=lambda
      # Setting this environment variable ensures that the config file
      # (and not just any credentials file that is present) is loaded.
      - AWS_SDK_LOAD_CONFIG=1
    image: cisagov/scanner:1.4.0
    secrets:
      - source: aws_config
        target: aws_config
    volumes:
      - ./output:/home/cisa/shared
  trustymail_report:
    depends_on:
      - redis
    environment:
      - AWS_CONFIG_FILE=/run/secrets/aws_config
      - AWS_PROFILE=elasticsearch
      # Setting this environment variable ensures that the config file
      # (and not just any credentials file that is present) is loaded.
      - AWS_SDK_LOAD_CONFIG=1
    image: cisagov/trustymail_reporter:1.7.2
    secrets:
      - source: aws_config
        target: aws_config
      - source: scan_read_creds
        target: scan_read_creds.yml
    volumes:
      - ./output:/home/cisa/shared
