version: '3.2'

secrets:
  cyhy_read_creds:
    file: ./secrets/cyhy_read_creds.yml
  pshtt_read_creds:
    file: ./secrets/pshtt_read_creds.yml
  pshtt_write_creds:
    file: ./secrets/pshtt_write_creds.yml
  trustymail_read_creds:
    file: ./secrets/trustymail_read_creds.yml
  trustymail_write_creds:
    file: ./secrets/trustymail_write_creds.yml
  sslyze_read_creds:
    file: ./secrets/sslyze_read_creds.yml
  sslyze_write_creds:
    file: ./secrets/sslyze_write_creds.yml
  aws_config:
    file: ./secrets/aws/config
  aws_creds:
    file: ./secrets/aws/credentials

services:
  redis:
    image: 'redis:alpine'
    # ports:
    #   - target: 6379
    #     published: 6379
    #     protocol: tcp
    #     mode: host
  gather:
    image: 'dhsncats/gatherer:latest'
    depends_on:
      - redis
    secrets:
      - source: cyhy_read_creds
        target: database_creds.yml
    volumes:
      - /tmp:/home/gatherer/shared
  scan:
    image: 'dhsncats/scanner:latest'
    depends_on:
      - redis
    secrets:
      - source: aws_config
        target: aws_config
      - source: aws_creds
        target: aws_creds
    environment:
      - AWS_CONFIG_FILE=/run/secrets/aws_config
      - AWS_SHARED_CREDENTIALS_FILE=/run/secrets/aws_creds
      - AWS_PROFILE=default
    volumes:
      - /tmp:/home/scanner/shared
    dns:
     - 8.8.8.8
  save:
    image: 'dhsncats/saver:latest'
    depends_on:
      - redis
    secrets:
      - source: pshtt_write_creds
        target: pshtt_write_creds.yml
      - source: trustymail_write_creds
        target: trustymail_write_creds.yml
      - source: sslyze_write_creds
        target: sslyze_write_creds.yml
    volumes:
      - /tmp:/home/saver/shared
  trustymail_report:
    image: 'dhsncats/trustymail_reporter:latest'
    depends_on:
      - redis
    secrets:
      - source: trustymail_read_creds
        target: trustymail_read_creds.yml
      - source: sslyze_read_creds
        target: sslyze_read_creds.yml
    volumes:
      - /tmp:/home/reporter/shared
  pshtt_report:
    image: 'dhsncats/pshtt_reporter:latest'
    depends_on:
      - redis
    secrets:
      - source: pshtt_read_creds
        target: pshtt_read_creds.yml
      - source: sslyze_read_creds
        target: sslyze_read_creds.yml
    volumes:
      - /tmp:/home/reporter/shared
