version: '3.2'

secrets:
  cyhy_read_creds:
    file: ./secrets/cyhy_read_creds.yml
  scan_read_creds:
    file: ./secrets/scan_read_creds.yml
  scan_write_creds:
    file: ./secrets/scan_write_creds.yml
  aws_config:
    file: ./secrets/aws_config

services:
  redis:
    image: 'redis:alpine'
    # ports:
    #   - target: 6379
    #     published: 6379
    #     protocol: tcp
    #     mode: host
  gather:
    image: 'cisagov/gatherer:1.3.0'
    depends_on:
      - redis
    secrets:
      - source: cyhy_read_creds
        target: database_creds.yml
    volumes:
      - ./output:/home/gatherer/shared
  scan:
    image: 'cisagov/scanner:1.2.3'
    depends_on:
      - redis
    secrets:
      - source: aws_config
        target: aws_config
    environment:
      - AWS_CONFIG_FILE=/run/secrets/aws_config
      - AWS_PROFILE=lambda
    volumes:
      - ./output:/home/scanner/shared
  save:
    image: 'cisagov/saver:1.2.1'
    depends_on:
      - redis
    secrets:
      - source: scan_write_creds
        target: scan_write_creds.yml
    volumes:
      - ./output:/home/saver/shared
  trustymail_report:
    image: 'cisagov/trustymail_reporter:1.1.18'
    depends_on:
      - redis
    secrets:
      - source: scan_read_creds
        target: scan_read_creds.yml
      - source: aws_config
        target: aws_config
    environment:
      - AWS_CONFIG_FILE=/run/secrets/aws_config
      - AWS_PROFILE=elasticsearch
    volumes:
      - ./output:/home/reporter/shared
  pshtt_report:
    image: 'cisagov/pshtt_reporter:1.1.11'
    depends_on:
      - redis
    secrets:
      - source: scan_read_creds
        target: scan_read_creds.yml
    volumes:
      - ./output:/home/reporter/shared
