version: '3.2'

secrets:
  cyhy_read_creds:
    file: ./secrets/cyhy_read_creds.yml
  scan_read_creds:
    file: ./secrets/scan_read_creds.yml
  scan_write_creds:
    file: ./secrets/scan_write_creds.yml
  aws_config:
    file: ./secrets/aws/config
  aws_creds:
    file: ./secrets/aws/credentials

services:
  redis:
    image: 'redis:alpine'
    # ports:
    #   - target: 6379
    #     published: 6379
    #     protocol: tcp
    #     mode: host
  gather:
    image: 'dhsncats/gatherer:1.0.0'
    depends_on:
      - redis
    secrets:
      - source: cyhy_read_creds
        target: database_creds.yml
    volumes:
      - ./output:/home/gatherer/shared
  scan:
    image: 'dhsncats/scanner:1.0.1'
    depends_on:
      - redis
    secrets:
      - source: aws_config
        target: aws_config
      - source: aws_creds
        target: aws_creds
    environment:
      - AWS_CONFIG_FILE=/run/secrets/aws_config
      - AWS_SHARED_CREDENTIALS_FILE=/run/secrets/aws_creds
      - AWS_PROFILE=default
    volumes:
      - ./output:/home/scanner/shared
    dns:
     - 8.8.8.8
  save:
    image: 'dhsncats/saver:1.0.3'
    depends_on:
      - redis
    secrets:
      - source: scan_write_creds
        target: scan_write_creds.yml
    volumes:
      - ./output:/home/saver/shared
  trustymail_report:
    image: 'dhsncats/trustymail_reporter:1.0.1'
    depends_on:
      - redis
    secrets:
      - source: scan_read_creds
        target: scan_read_creds.yml
    volumes:
      - ./output:/home/reporter/shared
  pshtt_report:
    image: 'dhsncats/pshtt_reporter:1.0.2'
    depends_on:
      - redis
    secrets:
      - source: scan_read_creds
        target: scan_read_creds.yml
    volumes:
      - ./output:/home/reporter/shared
